nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'API for managing blog articles'
            version: '1.0.0'
    routes:
        path: /api/doc
        host: ~
        schemes: [http, https]
        defaults: { _format: json }

