security:
    # Password hashers configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\User  # Adjust this to your User entity
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall for the API
        api:
            pattern: ^/api  # Protect routes starting with /api
            stateless: true  # No session is used for API
            provider: app_user_provider  # Use the app user provider
            jwt:  # Use JWT authentication
                provider: app_user_provider

        # Main firewall for web
        main:
            lazy: true
            provider: users_in_memory

    # Access control rules
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow anonymous access for login
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }  # Protect all other API routes

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
